### PR TITLE
Spanish translations

### PR DESCRIPTION
**Pull request by Bksp**
I did the translations of the book into Spanish but they don't appear....

### CODE REVIEW

**Comment by alRex-U** [comment]
Thanks, but sorry, I am just planning to change the internal structure of ParCool guide in next update. Thus if possible, could you re-translate it? 

If not possible, probably I can not add your translation to newer versions. I may be able to edit your translation for new system but I am not sure the content would be correct.

**Comment by Bksp** [comment]
Uh, nothing happens this mod gives color to my server (and my life) count on me to translate it!  (I hope it comes out in 1.19.2)

**Comment by Bksp** [comment]
in fact it's more, I integrated this mod to my Resource Pack "Minimalist GUI" if you want take a look

https://github.com/Bksp/Minimalist-GUI

**Comment by alRex-U** [comment]
Thanks, I will let you know in the language support issue (or here?) when new system is decided and available. Maybe it comes in February.

**Pull request closed without merging**
